### ISSUE TITLE
Change cabal description to reflect state of highlighter? 

### ISSUE THREAD

**Issue by teh** [chemist/highlighter#2]
Hey, thanks for updating the package!

Would you mind changing the description of the package to reflect whether this is a fork and if so: why? (I suspect the old package is unmaintained?)

**Comment by chemist** [comment]
Changes for performance when highlight big files (> 1000 lines of code).
My version work faster (5 - 10 times).
I send letter, and write  message in github to author, but he does not answer.

**Comment by chemist** [comment]
Change description, and up version.

**Comment by teh** [comment]
Thank you, super useful!
